apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wbstack-com-tls-staging
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  commonName: '*.wbstack.com'
  dnsNames:
  - wbstack.com
  - '*.wbstack.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: wbstack-com-tls-staging