apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opencura-com-tls
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  commonName: '*.opencura.com'
  dnsNames:
  - '*.opencura.com'
  - '*.wiki.opencura.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: opencura-com-tls-prod