apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wbstack-com-tls
  namespace: default
  resourceVersion: "220378891"
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  commonName: '*.wbstack.com'
  dnsNames:
  - wbstack.com
  - '*.wbstack.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: wbstack-com-tls-prod