apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # The solver defined earlier in the list will be used first according to docs:
      # https://cert-manager.io/docs/release-notes/release-notes-0.9/#dns-zones-support-for-acme-challenge-solver-selector
    - http01:
        ingress:
          class: nginx
      selector: {}
    - dns01:
        cloudDNS:
          # The project in which to update the DNS zone
          project: wbstack
          # A secretKeyRef to a google cloud json service account
          serviceAccountSecretRef:
            key: key.json
            name: clouddns-dns01-solver-svc-acct
      selector:
        dnsNames:
        - wbstack.com
        - '*.wbstack.com'
        - opencura.com
        - '*.opencura.com'
        - '*.wiki.opencura.com'
        - '*.wikibase.opencura.com'
        - '*.test.opencura.com'
